### ISSUE TITLE
SOTS results 

### ISSUE THREAD

**Issue by sudraj2002** [pwp1208/Domain_Translation_Multi-weather_Restoration#4]
Hi, I am trying to reproduce the results for SOTS. I put the SOTS hazy images in dataset/ and the ran the test.py script. I then calculated the PSNR and SSIM of the saved images. I am getting a PSNR of 31.97dB with SSIM of 0.95. Can you please tell if I am doing something wrong?

**Comment by pwp1208** [comment]
There are two things:
1. We have used SOTS outdoor database for testing.
2. Quantitative results are calculated with MATLAB inbuilt functions for PSNR and SSIM.
Please check with these settings.

**Comment by sudraj2002** [comment]
Thanks for your reply. I am using the SOTS outdoor database. I am getting the same PSNR with MATLAB as well.

**Comment by pwp1208** [comment]
Make sure you are calculating the PSNR on luminance (Y) channel after converting the RGB image to YCbCr.

**Comment by sudraj2002** [comment]
Thanks it works now.

**Comment by jiaqixuac** [comment]
I want to know if the metrics (including non-reference metrics) are computed based on the resized shape (256*256) or original shapes.
I find there is a crop and resize operation during the loading of the image.

**Comment by pwp1208** [comment]
All the metrics are calculated by resizing the output images to 256*256.
