### ISSUE TITLE
Evaluation Image Size

### ISSUE THREAD

**Issue by jiaqixuac** [pwp1208/Domain_Translation_Multi-weather_Restoration#5]
Thanks for your inspiring work!!

I want to know if the metrics (including PSNR, SSIM, and non-reference metrics) are computed based on the resized shape (256*256) or original shapes.
I find there is a crop and resize operation during the loading of the image.

Many thanks for your help!

**Comment by pwp1208** [comment]
All the metrics are calculated by resizing the output images to 256*256.
