### ISSUE TITLE
Questions about training detail

### ISSUE THREAD

**Issue by pp00704831** [pwp1208/Domain_Translation_Multi-weather_Restoration#6]
Hello,

I want to retrain your model and have some questions about training details.
1. How many **epochs** or **iterations** and **batch size** did you use for training Domain Translation (DT) and Restoration Generator (RG).
2. Did you train the Domain Translations first and then fixed them when training Restoration Generator?

Looking forward to your reply. Thank you very much.

**Comment by pwp1208** [comment]
Hi,
1. We trained the domain translation and restoration generator for 250 and 400 epochs respectively with batch size 10.
2. Yes. We train domain transaltion first and then fixed them while restoration generator training.
