### ISSUE TITLE
About the low-light enhancement issue of the model

### ISSUE THREAD

**Issue by WangL0ngTa0** [pwp1208/Domain_Translation_Multi-weather_Restoration#7]
Hello，Bro：
     I ran your model and found that it also has an enhancement effect on low-light photos, is it related to the dehazing model you trained? 
     Looking forward to your reply. 
![1710130796644](https://github.com/pwp1208/Domain_Translation_Multi-weather_Restoration/assets/148596559/ebd0f8f9-1930-40e0-aca0-c58ad41eda71)

**Comment by WangL0ngTa0** [comment]
But there is a certain gap between the output image and the original image
![Uploading 1710130977423.png…]()

**Comment by WangL0ngTa0** [comment]
But there is a certain gap between the output image and the original image
![1710130977423](https://github.com/pwp1208/Domain_Translation_Multi-weather_Restoration/assets/148596559/6f63f8a2-4694-4956-8c39-1f3498e35bbd)

**Comment by pwp1208** [comment]
Hi,
it is not realted to any model.
As we have not considered any low-light images while training, definitely there will be a certain gap between output and original image.

**Comment by WangL0ngTa0** [comment]
> Hi,
> 
> it is not realted to any model.
> 
> As we have not considered any low-light images while training, definitely there will be a certain gap between output and original image.

But it will have a certain effect on this kind of dark image, my first comment came up with the image is the result of stopping your model output. What is the reason for this？

**Comment by WangL0ngTa0** [comment]
> Hi,
> 
> it is not realted to any model.
> 
> As we have not considered any low-light images while training, definitely there will be a certain gap between output and original image.

> OK，thank you very much. Wish you a happy life！
