### ISSUE TITLE
About the paper experimental data

### ISSUE THREAD

**Issue by WangL0ngTa0** [pwp1208/Domain_Translation_Multi-weather_Restoration#9]
Hey Bro：
      I want to reproduce the experimental data of your paper, may I ask your NIQE and other results, is the input dataset picture adjusted to 256*256 test?
![image](https://github.com/pwp1208/Domain_Translation_Multi-weather_Restoration/assets/148596559/e724cdd7-f588-4e19-96fc-6c294cea5e36)

**Comment by pwp1208** [comment]
Hi,
While testing all the images are resized to 256*256*3.

**Comment by WangL0ngTa0** [comment]
ok，bro

**Comment by WangL0ngTa0** [comment]
Hello, I tested the PSNR of the 492 pairs of pictures in the SOTS_outdoor according to your paper method, and I found that the measured PSNR is less than the value given on your paper?What is the reason for this?I also converted all the pictures to 256*256*3 format, I would be grateful if you could guide me!
![1714214123321](https://github.com/pwp1208/Domain_Translation_Multi-weather_Restoration/assets/148596559/6be28c52-2f1e-490f-ac56-3688a32b3837)

**Comment by WangL0ngTa0** [comment]
Hello, I tested the PSNR of the 492 pairs of pictures in the SOTS_outdoor according to your paper method, and I found that the measured PSNR is less than the value given on your paper?What is the reason for this?I also converted all the pictures to 2562563 format, I would be grateful if you could guide me!
![1714214218294](https://github.com/pwp1208/Domain_Translation_Multi-weather_Restoration/assets/148596559/18bf6a73-9565-4864-b861-14e5d83cc0e3)
![1714214243563](https://github.com/pwp1208/Domain_Translation_Multi-weather_Restoration/assets/148596559/40b461ed-3c1a-47f8-8e05-7fc885be570f)

**Comment by WangL0ngTa0** [comment]
Hello, I tested the PSNR of the 492 pairs of pictures in the SOTS_outdoor according to your paper method, and I found that the measured PSNR is less than the value given on your paper?What is the reason for this?I also converted all the pictures to 256*256*3 format, I would be grateful if you could guide me!
![1714214626926](https://github.com/pwp1208/Domain_Translation_Multi-weather_Restoration/assets/148596559/fb14e2ba-7ec4-4f93-847f-26b13105072f)
![1714214654559](https://github.com/pwp1208/Domain_Translation_Multi-weather_Restoration/assets/148596559/7bceb468-3062-47cb-af94-1dfc479a5b59)

**Comment by WangL0ngTa0** [comment]
Hello, I tested the PSNR of the 492 pairs of pictures in the SOTS_outdoor according to your paper method, and I found that the measured PSNR is less than the value given in your paper?What is the reason for this?I first converted all the pictures input to the model into 256*256*3 format, and then output a clean image through the model you posted, and finally tested the PSNR and SSIM between the output image and the label image, I would be grateful if you could give me guidance!
![1714217357535](https://github.com/pwp1208/Domain_Translation_Multi-weather_Restoration/assets/148596559/047ef22c-9b23-4260-af2e-f8bd1ac4b01b)
![1714217375207](https://github.com/pwp1208/Domain_Translation_Multi-weather_Restoration/assets/148596559/048c5fbd-1af1-407c-8530-dce24e120c50)

**Comment by pwp1208** [comment]
Hi,
We used 500 outdoor images for testing in .png format.
Also, we calculated all the parameters on MATLAB.
Hopefully with these changes you will get the appropriate results.

**Comment by WangL0ngTa0** [comment]
thank you，thank you very much

**Comment by WangL0ngTa0** [comment]
Hello authors, I have some obstacles in recovering PSNR and SSIM, can you share the MATLAB code of your evaluation with me? I would appreciate it if you could share it with me!  my gmail ：yesimwlt@gmail.com

**Comment by pwp1208** [comment]
I hope you have received it.

**Comment by WangL0ngTa0** [comment]
of course. Thank you very much.
